#Thu Jul 03 01:05:38 COT 2025
org.gradle.caching=true
systemProp.version=3.23.1
package=co.com.bancolombia
language=java
org.gradle.parallel=true
lombok=true
org.gradle.configuration-cache.parallel=true
analytics=false
reactive=true
org.gradle.configuration-cache.integrity-check=true
metrics=false
org.gradle.configuration-cache=true
systemProp.sonar.gradle.skipCompile=true
